DELIMITER //

DROP PROCEDURE IF EXISTS `vidlinkdwnupd`;
CREATE  PROCEDURE `vidlinkdwnupd` ()

BEGIN
DECLARE varID INT;
DECLARE varURL VARCHAR(250);
DECLARE done INT DEFAULT FALSE;

DECLARE curs1 CURSOR FOR SELECT `id`, `url` FROM vidlinks;
DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = TRUE;

OPEN curs1;

read_loop: LOOP

FETCH curs1 INTO varID, varURL;

INSERT INTO `dwnvidtbl` VALUES(varID, varURL, '');

IF done THEN
LEAVE read_loop;
END IF;

END LOOP;

CLOSE curs1;

END//

